#ifndef FLA_CHUNK_GATED_DELTA_RULE_BWD_DHU_STRUCT_H
#define FLA_CHUNK_GATED_DELTA_RULE_BWD_DHU_STRUCT_H

#include <cstdint>

#ifndef TORCH_MODE
#include "ascendc/host_api/tiling/template_argument.h"
#endif

namespace GDN {

#define CHUNK_DHU_STRATEGY_FIXED 0
#define CHUNK_DHU_STRATEGY_VARLEN 1
#define CHUNK_DHU_TPL_BF16 10
#define CHUNK_DHU_TPL_FP16 20
#define CHUNK_DHU_TPL_FP32 30

#ifndef TORCH_MODE
ASCENDC_TPL_ARGS_DECL(ChunkGatedDeltaRuleBwdDhu,
    ASCENDC_TPL_UINT_DECL(STRATEGY, 1, ASCENDC_TPL_UI_LIST, CHUNK_DHU_STRATEGY_FIXED, CHUNK_DHU_STRATEGY_VARLEN),
    ASCENDC_TPL_DTYPE_DECL(D_T_Q, CHUNK_DHU_TPL_BF16, CHUNK_DHU_TPL_FP16),
    ASCENDC_TPL_DTYPE_DECL(D_T_G, CHUNK_DHU_TPL_BF16, CHUNK_DHU_TPL_FP16, CHUNK_DHU_TPL_FP32),
    ASCENDC_TPL_UINT_DECL(V_DIM, 1, ASCENDC_TPL_UI_LIST, 128, 256),
    ASCENDC_TPL_UINT_DECL(CHUNK_SIZE, 1, ASCENDC_TPL_UI_LIST, 64, 128),
);

#define CHUNK_DHU_TPL_CASE(strategy, qtype, gtype, vdim, chunk) \
    ASCENDC_TPL_ARGS_SEL( \
        ASCENDC_TPL_UINT_SEL(STRATEGY, ASCENDC_TPL_UI_LIST, strategy), \
        ASCENDC_TPL_DTYPE_SEL(D_T_Q, qtype), \
        ASCENDC_TPL_DTYPE_SEL(D_T_G, gtype), \
        ASCENDC_TPL_UINT_SEL(V_DIM, ASCENDC_TPL_UI_LIST, vdim), \
        ASCENDC_TPL_UINT_SEL(CHUNK_SIZE, ASCENDC_TPL_UI_LIST, chunk))

ASCENDC_TPL_SEL(
    CHUNK_DHU_TPL_CASE(CHUNK_DHU_STRATEGY_FIXED, CHUNK_DHU_TPL_BF16, CHUNK_DHU_TPL_BF16, 128, 64),
    CHUNK_DHU_TPL_CASE(CHUNK_DHU_STRATEGY_FIXED, CHUNK_DHU_TPL_FP16, CHUNK_DHU_TPL_FP16, 128, 64),
    CHUNK_DHU_TPL_CASE(CHUNK_DHU_STRATEGY_FIXED, CHUNK_DHU_TPL_BF16, CHUNK_DHU_TPL_FP32, 128, 64),
    CHUNK_DHU_TPL_CASE(CHUNK_DHU_STRATEGY_FIXED, CHUNK_DHU_TPL_FP16, CHUNK_DHU_TPL_FP32, 128, 64),
    CHUNK_DHU_TPL_CASE(CHUNK_DHU_STRATEGY_FIXED, CHUNK_DHU_TPL_BF16, CHUNK_DHU_TPL_BF16, 256, 64),
    CHUNK_DHU_TPL_CASE(CHUNK_DHU_STRATEGY_FIXED, CHUNK_DHU_TPL_FP16, CHUNK_DHU_TPL_FP16, 256, 64),
    CHUNK_DHU_TPL_CASE(CHUNK_DHU_STRATEGY_FIXED, CHUNK_DHU_TPL_BF16, CHUNK_DHU_TPL_FP32, 256, 64),
    CHUNK_DHU_TPL_CASE(CHUNK_DHU_STRATEGY_FIXED, CHUNK_DHU_TPL_FP16, CHUNK_DHU_TPL_FP32, 256, 64),
    CHUNK_DHU_TPL_CASE(CHUNK_DHU_STRATEGY_FIXED, CHUNK_DHU_TPL_BF16, CHUNK_DHU_TPL_BF16, 128, 128),
    CHUNK_DHU_TPL_CASE(CHUNK_DHU_STRATEGY_FIXED, CHUNK_DHU_TPL_FP16, CHUNK_DHU_TPL_FP16, 128, 128),
    CHUNK_DHU_TPL_CASE(CHUNK_DHU_STRATEGY_FIXED, CHUNK_DHU_TPL_BF16, CHUNK_DHU_TPL_FP32, 128, 128),
    CHUNK_DHU_TPL_CASE(CHUNK_DHU_STRATEGY_FIXED, CHUNK_DHU_TPL_FP16, CHUNK_DHU_TPL_FP32, 128, 128),
    CHUNK_DHU_TPL_CASE(CHUNK_DHU_STRATEGY_FIXED, CHUNK_DHU_TPL_BF16, CHUNK_DHU_TPL_BF16, 256, 128),
    CHUNK_DHU_TPL_CASE(CHUNK_DHU_STRATEGY_FIXED, CHUNK_DHU_TPL_FP16, CHUNK_DHU_TPL_FP16, 256, 128),
    CHUNK_DHU_TPL_CASE(CHUNK_DHU_STRATEGY_FIXED, CHUNK_DHU_TPL_BF16, CHUNK_DHU_TPL_FP32, 256, 128),
    CHUNK_DHU_TPL_CASE(CHUNK_DHU_STRATEGY_FIXED, CHUNK_DHU_TPL_FP16, CHUNK_DHU_TPL_FP32, 256, 128),
    CHUNK_DHU_TPL_CASE(CHUNK_DHU_STRATEGY_VARLEN, CHUNK_DHU_TPL_BF16, CHUNK_DHU_TPL_BF16, 128, 64),
    CHUNK_DHU_TPL_CASE(CHUNK_DHU_STRATEGY_VARLEN, CHUNK_DHU_TPL_FP16, CHUNK_DHU_TPL_FP16, 128, 64),
    CHUNK_DHU_TPL_CASE(CHUNK_DHU_STRATEGY_VARLEN, CHUNK_DHU_TPL_BF16, CHUNK_DHU_TPL_FP32, 128, 64),
    CHUNK_DHU_TPL_CASE(CHUNK_DHU_STRATEGY_VARLEN, CHUNK_DHU_TPL_FP16, CHUNK_DHU_TPL_FP32, 128, 64),
    CHUNK_DHU_TPL_CASE(CHUNK_DHU_STRATEGY_VARLEN, CHUNK_DHU_TPL_BF16, CHUNK_DHU_TPL_BF16, 256, 64),
    CHUNK_DHU_TPL_CASE(CHUNK_DHU_STRATEGY_VARLEN, CHUNK_DHU_TPL_FP16, CHUNK_DHU_TPL_FP16, 256, 64),
    CHUNK_DHU_TPL_CASE(CHUNK_DHU_STRATEGY_VARLEN, CHUNK_DHU_TPL_BF16, CHUNK_DHU_TPL_FP32, 256, 64),
    CHUNK_DHU_TPL_CASE(CHUNK_DHU_STRATEGY_VARLEN, CHUNK_DHU_TPL_FP16, CHUNK_DHU_TPL_FP32, 256, 64),
    CHUNK_DHU_TPL_CASE(CHUNK_DHU_STRATEGY_VARLEN, CHUNK_DHU_TPL_BF16, CHUNK_DHU_TPL_BF16, 128, 128),
    CHUNK_DHU_TPL_CASE(CHUNK_DHU_STRATEGY_VARLEN, CHUNK_DHU_TPL_FP16, CHUNK_DHU_TPL_FP16, 128, 128),
    CHUNK_DHU_TPL_CASE(CHUNK_DHU_STRATEGY_VARLEN, CHUNK_DHU_TPL_BF16, CHUNK_DHU_TPL_FP32, 128, 128),
    CHUNK_DHU_TPL_CASE(CHUNK_DHU_STRATEGY_VARLEN, CHUNK_DHU_TPL_FP16, CHUNK_DHU_TPL_FP32, 128, 128),
    CHUNK_DHU_TPL_CASE(CHUNK_DHU_STRATEGY_VARLEN, CHUNK_DHU_TPL_BF16, CHUNK_DHU_TPL_BF16, 256, 128),
    CHUNK_DHU_TPL_CASE(CHUNK_DHU_STRATEGY_VARLEN, CHUNK_DHU_TPL_FP16, CHUNK_DHU_TPL_FP16, 256, 128),
    CHUNK_DHU_TPL_CASE(CHUNK_DHU_STRATEGY_VARLEN, CHUNK_DHU_TPL_BF16, CHUNK_DHU_TPL_FP32, 256, 128),
    CHUNK_DHU_TPL_CASE(CHUNK_DHU_STRATEGY_VARLEN, CHUNK_DHU_TPL_FP16, CHUNK_DHU_TPL_FP32, 256, 128),
);
#undef CHUNK_DHU_TPL_CASE
#endif

struct ChunkGatedDeltaRuleBwdDhuTilingData {
    uint64_t b;
    uint64_t hk;
    uint64_t hv;
    uint64_t t;
    uint64_t k;
    uint64_t v;
    uint64_t chunk;
    uint64_t chunks;
    uint64_t seqs;
    uint64_t varlen;
    uint64_t has_g;
    uint64_t has_gk;
    uint64_t has_h0;
    uint64_t has_dht;
    uint64_t state_bytes;
    uint64_t matrix_bytes;
    uint64_t slot_bytes;
    uint32_t used_core;
    float scale;
};

} // namespace GDN
#endif
